name: Handle Presence in my Woffu Account

# on: [push]

on:
  schedule:
    # Mon to Thu
    - cron:  '0 8 * * 1-4' # morning check-in
    - cron:  '0 14 * * 1-4' # morning check-out
    - cron:  '30 14 * * 1-4' # lunch check-in
    - cron:  '0 17 * * 1-4' # finish day
    # Fri
    - cron:  '0 8 * * 5' # morning check-in
    - cron:  '0 14 * * 5' # finish day

jobs:
  toggle-presence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install
        run: npm install
      - name: Run
        run: npm run start
