name: Handle Presence in my Woffu Account
on:
  schedule:
    - cron:  '* * * * *'
jobs:
  Toggle Presence:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.WOFFU_TOKEN }}
      ID: ${{ secrets.WOFFU_USER_ID }}
    steps:
      - run: curl https://liferay.woffu.com/api/svc/signs/signs -H 'Content-Type: application/json;charset=utf-8' -H 'Authorization: Bearer "%TOKEN%"' --data-raw '{"UserId":"%ID%","DeviceId":"WebApp"}'"
