name: Handle Presence in my Woffu Account

on: [push]

# on:
#   schedule:
#     # Mon to Thu
#     - cron: '45 6 * * 1-4' # morning check-in
#     - cron: '0 13 * * 1-4' # morning check-out
#     - cron: '30 13 * * 1-4' # lunch check-in
#     - cron: '0 16 * * 1-4' # finish day
#     # Fri
#     - cron: '0 7 * * 5' # morning check-in
#     - cron: '0 13 * * 5' # finish day

jobs:
  toggle-presence:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      RECIPIENT: ${{ secrets.RECIPIENT }}
      USER_NAME: ${{ secrets.USER_NAME }}
      WOFFU_ENDPOINT: ${{ secrets.WOFFU_ENDPOINT }}
      WOFFU_TOKEN: ${{ secrets.WOFFU_TOKEN }}
      WOFFU_USER_ID: ${{ secrets.WOFFU_USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install
        run: npm install
      - name: Run
        run: npm run start
