name: Handle Presence in my Woffu Account

# on: [push]

on:
  schedule:
    # WINTER TIME
    # Mon to Thu
    # - cron: '55 6 * * 1-4' # morning check-in
    # - cron: '02 13 * * 1-4' # morning check-out
    # - cron: '34 13 * * 1-4' # lunch check-in
    # - cron: '22 16 * * 1-4' # finish day
    # Fri
    # - cron: '57 6 * * 5' # morning check-in
    # - cron: '59 12 * * 5' # finish day

    # SUMMER TIME
    # Mon to Thu
    - cron: '55 5 * * 1-4' # morning check-in
    - cron: '02 12 * * 1-4' # morning check-out
    - cron: '34 12 * * 1-4' # lunch check-in
    - cron: '22 15 * * 1-4' # finish day
    # Fri
    - cron: '57 5 * * 5' # morning check-in
    - cron: '59 11 * * 5' # finish day

jobs:
  toggle-presence:
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      RECIPIENTS: ${{ secrets.RECIPIENTS }}
      USER_NAME: ${{ secrets.USER_NAME }}
      WOFFU_ENDPOINT: ${{ secrets.WOFFU_ENDPOINT }}
      WOFFU_TOKEN: ${{ secrets.WOFFU_TOKEN }}
      WOFFU_USER_ID: ${{ secrets.WOFFU_USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
      - name: Install
        run: npm install
      - name: Run
        run: npm run start
